export const JUKI_SUBMISSIONS_RESOLVE_SERVICE_BASE_URL = process.env.NEXT_PUBLIC_JUKI_SUBMISSIONS_RESOLVE_SERVICE_BASE_URL;
export const API_VERSION = 'api/v1';
export const JUKI_TOKEN_NAME = process.env.NEXT_PUBLIC_JUKI_TOKEN_NAME || '';
export const JUKI_LOW_RUNNER_TASK_DEFINITION_FAMILY_NAME = process.env.NEXT_PUBLIC_JUKI_LOW_RUNNER_TASK_DEFINITION_FAMILY_NAME || '';
export const JUKI_HIGH_RUNNER_TASK_DEFINITION_FAMILY_NAME = process.env.NEXT_PUBLIC_JUKI_HIGH_RUNNER_TASK_DEFINITION_FAMILY_NAME || '';
