import { Language, TextLanguageType } from 'types';

export const EMPTY_TEXT_LANGUAGES: TextLanguageType = { [Language.ES]: '', [Language.EN]: '' };

export {
  ALPHANUMERIC_DASH_UNDERSCORE_REGEX,
  DEFAULT_DATA_VIEWER_PROPS,
  EMPTY_ORGANIZATION,
  EMPTY_USER,
} from '@juki-team/base-ui/constants';

export { EMPTY_ORGANIZATION as EMPTY_COMPANY } from '@juki-team/base-ui/constants';

export {
  PROBLEM_TYPE,
  PROBLEM_VERDICT,
  PROBLEM_MODE,
  ENTITY_ACCESS,
  ACCEPTED_PROGRAMMING_LANGUAGES,
  RUNNER_ACCEPTED_PROBLEM_MODES,
  RUNNER_ACCEPTED_PROBLEM_TYPES,
  JUDGE,
  PALETTE,
  USER_ROLE,
  PROBLEM_ROLE,
  CONTEST_ROLE,
  TEAM_ROLE,
  COURSE_ROLE,
  LANGUAGE,
  CONTEST_STATUS,
  MAX_DATE,
  MIN_DATE,
  RUNNER_ACCEPTED_PROGRAMMING_LANGUAGES,
  JUKI_APP_ORGANIZATION_KEY,
  ORGANIZATION_PLAN,
  PROBLEM_TYPES,
  EMPTY_USER_PERMISSIONS,
  EMPTY_ENTITY_MEMBERS,
  EMPTY_DOCUMENT_MEMBERS,
  MONTH_NAMES,
  CODE_LANGUAGE,
  ONE_MINUTE,
  SEPARATOR_TOKEN,
  ONE_SECOND,
  HEADER_JUKI_FORWARDED_HOST,
  HEADER_JUKI_INTERNAL_API_KEY,
} from '@juki-team/commons/constants';

export {
  PALETTE as PALLETE,
  JUKI_APP_ORGANIZATION_KEY as JUKI_APP_COMPANY_KEY,
  ORGANIZATION_PLAN as COMPANY_PLAN,
  ERROR_HTTP_STATUS as ERROR,
} from '@juki-team/commons/constants';
